Update Readme with Usage Documentation
solidusio-contrib/solidus_reports pull request #28
Opened 2020-09-02 15:40 UTC by asecondwill

Some docs to help users get going.

2020-09-07 07:29 UTC, aldesantis commented
@asecondwill thanks! Just one thing: could you format the code with syntax highlighting? The syntax for doing that is the following:

    ```ruby
    put code here...
    ```

2020-09-23 05:32 UTC, asecondwill commented
ok, that should be done

2020-09-23 07:23 UTC, aldesantis requested changes
Thanks! Left a few more comments on things I had missed in my first pass. Good to go once fixed!

2020-09-23 07:23 UTC, aldesantis commented on README.md
> +````
There's an extra backtick here, it should be three.

2020-09-23 07:23 UTC, aldesantis commented on README.md
> +
Extra blank line here.

2020-09-23 07:23 UTC, aldesantis commented on README.md
> +Add an entry into your Translations
This should be "Add an entry to your translations". 🙂

2020-11-29 09:57 UTC, closed without merging