Add support for v4
solidusio-contrib/solidus_reports pull request #47
Opened 2023-07-08 03:46 UTC by jtapia

2023-09-26 07:02 UTC, tvdeyen requested changes
Thanks for your contribution. Could you please create single commits for each change and explain why a change was necessary. Also, there is a change in tested ruby version. Why has this changed be made and can you please revert it?

2023-09-26 07:02 UTC, tvdeyen commented on .github_changelog_generator
> +exclude-labels=infrastructure
Where does this change came from? Can you make this a separate commit.

2023-09-26 07:02 UTC, tvdeyen commented on .rubocop.yml
> +  NewCops: disable
This change also qualifies a separate commit

2026-04-01 15:22 UTC, adammathys commented
Resolved by https://github.com/solidusio-contrib/solidus_reports/pull/51

2026-04-01 15:22 UTC, closed without merging